// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQbwD2BwwEfWtk2xcWANjkPcBdfmIqi8',
    appId: '1:676023959863:web:64c1dd6056a3c9f4bb5ab2',
    messagingSenderId: '676023959863',
    projectId: 'bayani-79675',
    authDomain: 'bayani-79675.firebaseapp.com',
    databaseURL: 'https://bayani-79675-default-rtdb.firebaseio.com',
    storageBucket: 'bayani-79675.appspot.com',
    measurementId: 'G-NRP32F74PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM25DVgNTIZqjIkq9WjJfocstGPs72vBw',
    appId: '1:676023959863:android:627bc8cb58cf184dbb5ab2',
    messagingSenderId: '676023959863',
    projectId: 'bayani-79675',
    databaseURL: 'https://bayani-79675-default-rtdb.firebaseio.com',
    storageBucket: 'bayani-79675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEXrvamDn31Tq9K1czMOwnxiPg5KapcNw',
    appId: '1:676023959863:ios:d0ecd1c61fe29630bb5ab2',
    messagingSenderId: '676023959863',
    projectId: 'bayani-79675',
    databaseURL: 'https://bayani-79675-default-rtdb.firebaseio.com',
    storageBucket: 'bayani-79675.appspot.com',
    androidClientId: '676023959863-bv7s5bncl7ojjflb2ratua6ilvob4npt.apps.googleusercontent.com',
    iosClientId: '676023959863-qeh4hvi2jo3n9rroi9u0s6abtcu1b5ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.responder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEXrvamDn31Tq9K1czMOwnxiPg5KapcNw',
    appId: '1:676023959863:ios:d0ecd1c61fe29630bb5ab2',
    messagingSenderId: '676023959863',
    projectId: 'bayani-79675',
    databaseURL: 'https://bayani-79675-default-rtdb.firebaseio.com',
    storageBucket: 'bayani-79675.appspot.com',
    androidClientId: '676023959863-bv7s5bncl7ojjflb2ratua6ilvob4npt.apps.googleusercontent.com',
    iosClientId: '676023959863-qeh4hvi2jo3n9rroi9u0s6abtcu1b5ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.responder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUQbwD2BwwEfWtk2xcWANjkPcBdfmIqi8',
    appId: '1:676023959863:web:5f3c4c4793bb9143bb5ab2',
    messagingSenderId: '676023959863',
    projectId: 'bayani-79675',
    authDomain: 'bayani-79675.firebaseapp.com',
    databaseURL: 'https://bayani-79675-default-rtdb.firebaseio.com',
    storageBucket: 'bayani-79675.appspot.com',
    measurementId: 'G-KRG6MPYV3S',
  );
}
